source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Internet_Example', :exclusive => true do
  pod "Internet", :path => "../"
end

target 'Internet_Tests', :exclusive => true do
  pod "Internet", :path => "../"

  
end
